[project]
name = "rts-basic-methods"
version = "0.1.0"
description = "RTS methods"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "PyLaTeX>=1.3.4",
    "simso",
    "tabulate"
]


